name: Build and Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 4.8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.8.x'
      - name: Display .NET version
        run: dotnet --version
      # Add other build and run steps here
